<a href="https://colab.research.google.com/github/francisco0987/Site/blob/master/mnist_iniciante.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [9]:
# Carregando e preparando o conjunto de dados
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) =mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [12]:
# Criando o modelo
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)                                
])

In [13]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.5266482 ,  0.3089517 , -0.2875143 ,  0.6157279 ,  0.07525381,
         0.28574032,  0.5205529 , -0.16008472, -0.12522435,  0.23704225]],
      dtype=float32)

In [14]:
# A tf.nn.softmaxfunção converte esses logits em "probabilidades"
# para cada classe
tf.nn.softmax(predictions).numpy()

array([[0.13280267, 0.10682242, 0.05883293, 0.14517559, 0.08456073,
        0.10437147, 0.13199565, 0.06682862, 0.06919937, 0.09941056]],
      dtype=float32)

In [18]:
#A losses.SparseCategoricalCrossentropyperda pega um vetor de logits 
#e um Trueíndice e retorna uma perda escalar para cada exemplo.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.2597988

In [19]:
# Compilando o modelo
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [21]:
# O Model.fitmétodo ajusta os parâmetros do modelo para minimizar a perda:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2929 - accuracy: 0.9151
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1424 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1080 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0888 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0748 - accuracy: 0.9766


In [23]:
# O Model.evaluatemétodo verifica o desempenho dos modelos, geralmente 
#em um " conjunto de validação " ou " conjunto de teste ".
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0725 - accuracy: 0.9787


[0.07250433415174484, 0.9786999821662903]

In [24]:
# Faz o modelo retorna uma probabilidade
probability_model = tf.keras.Sequential([
     model,
     tf.keras.layers.Softmax()                                    
])

In [25]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.6400772e-07, 1.8458735e-08, 1.0796246e-05, 1.0742547e-04,
        1.5170380e-10, 1.0638225e-07, 7.7950466e-13, 9.9987948e-01,
        4.2303430e-08, 2.0180846e-06],
       [7.5133155e-10, 1.2067551e-03, 9.9849451e-01, 2.9801292e-04,
        2.9222939e-15, 3.3655088e-08, 4.9209004e-10, 1.1628224e-12,
        7.6654675e-07, 1.8037526e-14],
       [5.6369566e-07, 9.9932182e-01, 1.0627848e-04, 1.3253560e-05,
        4.2302487e-05, 4.1164881e-06, 2.8349075e-05, 4.4741668e-04,
        3.5137480e-05, 6.8628555e-07],
       [9.9954957e-01, 8.0838319e-08, 2.4988307e-05, 7.9882165e-07,
        6.7443597e-07, 1.2959653e-04, 2.7704320e-04, 1.3603241e-05,
        3.6695575e-08, 3.4941245e-06],
       [3.7052923e-06, 3.9485609e-08, 2.5383843e-05, 1.9649507e-07,
        9.7244722e-01, 1.7131839e-05, 1.0736061e-04, 1.3902495e-04,
        4.8622305e-06, 2.7255079e-02]], dtype=float32)>